# Stroke order filtering

Notebook helper to map one-character-per-line Chinese input to the existing stroke-order CSV, then derive the iframe embed HTML and image URL for each matched character.

In [1]:
from pathlib import Path
from typing import Iterable

import pandas as pd
from IPython.display import HTML, display

# CSV_PATH = Path(r"d:\repos\chinese-docs\docs\resources\List of Stroke Order Animation Embed URLs.csv")
CSV_PATH = Path("docs/resources/List of Stroke Order Animation Embed URLs.csv")
IMAGE_URL_TEMPLATE = "https://www.strokeorder.com/assets/bishun/guide/{id}.png"


def load_stroke_lookup(csv_path: Path = CSV_PATH) -> pd.DataFrame:
    df = pd.read_csv(csv_path, dtype=str)
    df.columns = ["no", "unicode_decimal", "character", "embed_html"]
    for column in df.columns:
        df[column] = df[column].astype(str).str.strip()
    df["image_url"] = df["unicode_decimal"].map(lambda value: IMAGE_URL_TEMPLATE.format(id=value))
    return df


def extract_characters(source: str | Path | Iterable[str]) -> list[str]:
    if isinstance(source, Path):
        text = source.read_text(encoding="utf-8")
    elif isinstance(source, str):
        if "\n" not in source and Path(source.strip()).exists():
            text = Path(source.strip()).read_text(encoding="utf-8")
        else:
            text = source
    else:
        text = "\n".join(str(item) for item in source)

    characters: list[str] = []
    seen: set[str] = set()
    for line in text.splitlines():
        character = line.strip()
        if len(character) != 1 or character in seen:
            continue
        seen.add(character)
        characters.append(character)
    return characters


def filter_stroke_entries(source: str | Path | Iterable[str], csv_path: Path = CSV_PATH) -> pd.DataFrame:
    characters = extract_characters(source)
    lookup = load_stroke_lookup(csv_path).set_index("character", drop=False)
    rows: list[dict[str, str]] = []

    for character in characters:
        if character not in lookup.index:
            continue
        record = lookup.loc[character]
        if isinstance(record, pd.DataFrame):
            record = record.iloc[0]
        rows.append(
            {
                "character": record["character"],
                "unicode_decimal": record["unicode_decimal"],
                "embed_html": record["embed_html"],
                "image_url": record["image_url"],
                "csv_no": record["no"],
            }
        )

    return pd.DataFrame(rows, columns=["character", "unicode_decimal", "embed_html", "image_url", "csv_no"])


def to_markdown_table(df: pd.DataFrame) -> str:
    if df.empty:
        return "| character | unicode_decimal | embed_html | image_url | csv_no |\n| --- | --- | --- | --- | --- |"

    header = "| " + " | ".join(df.columns) + " |"
    separator = "| " + " | ".join(["---"] * len(df.columns)) + " |"
    lines = [header, separator]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(str(row[column]) for column in df.columns) + " |")
    return "\n".join(lines)


def render_results(source: str | Path | Iterable[str], csv_path: Path = CSV_PATH) -> pd.DataFrame:
    result = filter_stroke_entries(source, csv_path=csv_path)
    display(result)
    display(HTML(result.to_html(index=False, escape=False)))
    print(to_markdown_table(result))
    return result

In [9]:
sample_input = """
人
越
南
中
国
名
字
"""

result = render_results(sample_input)
print("First matched row:")
print(result.iloc[0].to_dict())
print("Zero image URL:")
# print(result.loc[result["character"] == "零", "image_url"].iloc[0])

output_csv = Path("stroke_filtering_output.csv")
result.to_csv(output_csv, index=False, encoding="utf-8-sig")
print(f"Wrote {output_csv.resolve()}")

,character,unicode_decimal,embed_html,image_url,csv_no
0,人,20154,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,11
1,越,36234,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,3109
2,南,21335,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,1228
3,中,20013,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,71
4,国,22269,<image src='https://www.strokeorder.com/assets...,https://www.strokeorder.com/assets/bishun/guid...,22269
5,名,21517,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,348
6,字,23383,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,379

| character | unicode_decimal | embed_html | image_url | csv_no |
| --- | --- | --- | --- | --- |
| 人 | 20154 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=20154' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/20154.png | 11 |
| 越 | 36234 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=36234' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/36234.png | 3109 |
| 南 | 21335 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=21335' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/21335.png | 1228 |
| 中 | 20013 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=20013' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/20013.png | 71 |
| 国 | 22269 | <image src='https://www.strokeorder.com/assets/bishun/animation/22269.gif' width=300> | https://www.strokeorder.com/assets/bishun/guide/22269.png | 22269 |
| 名 | 21517 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=21517' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/21517.png | 348 |
| 字 | 23383 | <iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=23383' frameborder=0 width=300 height=520 allow='fullscreen'></iframe> | https://www.strokeorder.com/assets/bishun/guide/23383.png | 379 |
First matched row:
{'character': '人', 'unicode_decimal': '20154', 'embed_html': "<iframe src='https://stroke-order.learningweb.moe.edu.tw/dictFrame.jsp?ID=20154' frameborder=0 width=300 height=520 allow='fullscreen'></iframe>", 'image_url': 'https://www.strokeorder.com/assets/bishun/guide/20154.png', 'csv_no': '11'}
Zero image URL:
Wrote D:\repos\chinese-docs\stroke_filtering_output.csv

In [10]:
result

,character,unicode_decimal,embed_html,image_url,csv_no
0,人,20154,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,11
1,越,36234,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,3109
2,南,21335,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,1228
3,中,20013,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,71
4,国,22269,<image src='https://www.strokeorder.com/assets...,https://www.strokeorder.com/assets/bishun/guid...,22269
5,名,21517,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,348
6,字,23383,<iframe src='https://stroke-order.learningweb....,https://www.strokeorder.com/assets/bishun/guid...,379

In [11]:
print('''<div style="display:flex; overflow-x:auto; gap:10px;">''')
for _, row in result.iterrows():
    print(f'''<img src="{row["image_url"]}" alt="{row['character']}" width=300 onclick="speakSlow('{row['character']}')">''')
print("</div>")

<div style="display:flex; overflow-x:auto; gap:10px;">
<img src="https://www.strokeorder.com/assets/bishun/guide/20154.png" alt="人" width=300 onclick="speakSlow('人')">
<img src="https://www.strokeorder.com/assets/bishun/guide/36234.png" alt="越" width=300 onclick="speakSlow('越')">
<img src="https://www.strokeorder.com/assets/bishun/guide/21335.png" alt="南" width=300 onclick="speakSlow('南')">
<img src="https://www.strokeorder.com/assets/bishun/guide/20013.png" alt="中" width=300 onclick="speakSlow('中')">
<img src="https://www.strokeorder.com/assets/bishun/guide/22269.png" alt="国" width=300 onclick="speakSlow('国')">
<img src="https://www.strokeorder.com/assets/bishun/guide/21517.png" alt="名" width=300 onclick="speakSlow('名')">
<img src="https://www.strokeorder.com/assets/bishun/guide/23383.png" alt="字" width=300 onclick="speakSlow('字')">
</div>